"""Pydantic contracts for Planner LLM-generated static plan."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


PreconditionKind = Literal[
    "job_exists",
    "candidate_profile_exists",
    "resume_content_exists",
]
StepOnError = Literal["fail", "skip", "degrade"]


class PlannerPolicyOutput(BaseModel):
    """Execution policy generated by planner LLM."""

    model_config = ConfigDict(extra="forbid")

    fail_fast: bool = True
    partial_success: bool = False
    allow_degraded_completion: bool = False


class PlannerStepOutput(BaseModel):
    """One LLM-generated step draft before conversion into PlanStep."""

    model_config = ConfigDict(extra="forbid")

    key: str = Field(min_length=1)
    agent: str
    action: str
    intent: str
    reads: list[str] = Field(default_factory=list)
    writes: list[str] = Field(default_factory=list)
    depends_on: list[str] = Field(default_factory=list)
    preconditions: list[PreconditionKind] = Field(default_factory=list)
    retry_max_attempts: int = Field(default=1, ge=1, le=5)
    on_error: StepOnError = "fail"
    skippable: bool = False
    fallback_action: str = ""
    reason: str = ""


class PlannerPlanOutput(BaseModel):
    """Top-level planner output generated by LLM."""

    model_config = ConfigDict(extra="forbid")

    intent: str = "ask_question"
    intent_bundle: list[str] = Field(default_factory=list)
    policy: PlannerPolicyOutput = Field(default_factory=PlannerPolicyOutput)
    steps: list[PlannerStepOutput] = Field(default_factory=list)
